### ISSUE TITLE
Bugging displaying of the handle

### ISSUE THREAD

**Issue by raptus93** [RaghavSood/AndroidCircularSeekBar#16]
Hello everyone!

I have a problem using the CircularSeekBar that is strange for me: Everything works fine and looks great, until I change the text of the textView in the same relative layout.

I call this method in onProgressChange:
`private void updateStatus(int progress) {
        TextView tv = (TextView) findViewById(R.id.status_seekbar_noise);
        int hz = (int) calcHzFromPercent(progress);
        tv.setText(hz+" Hz");
    }`

If I remove the tv.setText()-method, everything works fine. If I try to use the line,
the handle of the seekbar jumps back to 0 degrees and then back to where it should be. This flattering happens all the time. So what is wrong with my code? Or is it the code in the CircularSeekBar-Class.

If anyone knows the solution please tell me.

Best regards and thanks for the great code!

**Comment by ArGaspar** [comment]
Hi!
im new on Android and im doing my best to make this work but 
I can`t even make it show the bar, could you share your xml file please.
Thanks
